// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using acessa_dev_web.Models;

#nullable disable

namespace acessa_dev_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106155242_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("acessa_dev_web.Models.Avaliacao", b =>
                {
                    b.Property<int>("idAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAvaliacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoAvaliacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorAvaliacao")
                        .HasColumnType("int");

                    b.Property<int>("idLocal")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idAvaliacao");

                    b.HasIndex("idLocal");

                    b.HasIndex("idUsuario");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Local", b =>
                {
                    b.Property<int>("idLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLocal"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLocal");

                    b.ToTable("Locais");

                    b.HasData(
                        new
                        {
                            idLocal = 1,
                            Endereco = "Praça da Sé, Centro, São Paulo - SP",
                            Latitude = -23.5505f,
                            Longitude = -46.6333f,
                            Nome = "Praça da Sé"
                        },
                        new
                        {
                            idLocal = 2,
                            Endereco = "Avenida Paulista, 1000, São Paulo - SP",
                            Latitude = -23.5631f,
                            Longitude = -46.654f,
                            Nome = "Avenida Paulista"
                        },
                        new
                        {
                            idLocal = 3,
                            Endereco = "Shopping Center Norte, Tucuruvi, São Paulo - SP",
                            Latitude = -23.4896f,
                            Longitude = -46.6104f,
                            Nome = "Shopping Center Norte"
                        },
                        new
                        {
                            idLocal = 4,
                            Endereco = "Parque Ibirapuera, Moema, São Paulo - SP",
                            Latitude = -23.5875f,
                            Longitude = -46.6576f,
                            Nome = "Parque Ibirapuera"
                        },
                        new
                        {
                            idLocal = 5,
                            Endereco = "Estação da Luz, Centro, São Paulo - SP",
                            Latitude = -23.535f,
                            Longitude = -46.634f,
                            Nome = "Estação da Luz"
                        });
                });

            modelBuilder.Entity("acessa_dev_web.Models.MediaAvaliacao", b =>
                {
                    b.Property<int>("idMediaAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMediaAvaliacao"));

                    b.Property<float>("AvaliacaoMedia")
                        .HasColumnType("real");

                    b.Property<int>("QtdAvaliacoes")
                        .HasColumnType("int");

                    b.Property<float>("VlUltimaAvaliacao")
                        .HasColumnType("real");

                    b.Property<float>("VlUltimaAvaliacaoMedia")
                        .HasColumnType("real");

                    b.Property<int>("idLocal")
                        .HasColumnType("int");

                    b.HasKey("idMediaAvaliacao");

                    b.HasIndex("idLocal");

                    b.ToTable("MediaAvaliacoes");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Ocorrencia", b =>
                {
                    b.Property<int>("idOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOcorrencia"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoOcorrencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("idLocal")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idOcorrencia");

                    b.HasIndex("idLocal");

                    b.HasIndex("idUsuario");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Nome = "Usuário Demo",
                            Perfil = 0,
                            Senha = "123456"
                        },
                        new
                        {
                            id = 2,
                            Nome = "Administrador",
                            Perfil = 2,
                            Senha = "admin123"
                        });
                });

            modelBuilder.Entity("acessa_dev_web.Models.Avaliacao", b =>
                {
                    b.HasOne("acessa_dev_web.Models.Local", "Local")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("idLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acessa_dev_web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("acessa_dev_web.Models.MediaAvaliacao", b =>
                {
                    b.HasOne("acessa_dev_web.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("idLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Ocorrencia", b =>
                {
                    b.HasOne("acessa_dev_web.Models.Local", "Local")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("idLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acessa_dev_web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Local", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
