// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using acessa_dev_web.Models;

#nullable disable

namespace acessa_dev_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("acessa_dev_web.Models.Avaliacao", b =>
                {
                    b.Property<int>("idAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAvaliacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoAvaliacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorAvaliacao")
                        .HasColumnType("int");

                    b.Property<int>("idLocal")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idAvaliacao");

                    b.HasIndex("idLocal");

                    b.HasIndex("idUsuario");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Local", b =>
                {
                    b.Property<int>("idLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLocal"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLocal");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("acessa_dev_web.Models.MediaAvaliacao", b =>
                {
                    b.Property<int>("idMediaAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMediaAvaliacao"));

                    b.Property<float>("AvaliacaoMedia")
                        .HasColumnType("real");

                    b.Property<int>("QtdAvaliacoes")
                        .HasColumnType("int");

                    b.Property<float>("VlUltimaAvaliacao")
                        .HasColumnType("real");

                    b.Property<int>("idLocal")
                        .HasColumnType("int");

                    b.HasKey("idMediaAvaliacao");

                    b.ToTable("MediaAvaliacoes");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Ocorrencia", b =>
                {
                    b.Property<int>("idOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOcorrencia"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoOcorrencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("idLocal")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idOcorrencia");

                    b.HasIndex("idLocal");

                    b.HasIndex("idUsuario");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Avaliacao", b =>
                {
                    b.HasOne("acessa_dev_web.Models.Local", "Local")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("idLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acessa_dev_web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Ocorrencia", b =>
                {
                    b.HasOne("acessa_dev_web.Models.Local", "Local")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("idLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acessa_dev_web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("acessa_dev_web.Models.Local", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
